CREATE DATABASE GROUP_PROJECT337;
USE GROUP_PROJECT337;

create table admin(
admin_id varchar(20) null unique,
email varchar(45) not null PRIMARY KEY,
password varchar(40)NOT NULL UNIQUE
);
CREATE TABLE employee_user(
employee_id varchar(9) NOT NULL UNIQUE ,
email varchar(45) not null UNIQUE PRIMARY KEY,
password varchar(45) not null);

CREATE TABLE Customer(
Customer_id varchar(15) Not null unique,
email varchar(50) NOT NULL UNIQUE PRIMARY KEY,
password varchar(40) NOT NULL);

CREATE TABLE CUSTOMER_INFO(
CUSTOMER_ID NOT NULL UNIQUE PRIMARY KEY,
FIRST_NAME VARCHAR(45) NOT NULL,
M_NAME CHAR(1),
LAST_NAME VARCHAR(45) NOT NULL,
DATE_BIRTH DATE NOT NULL,
GENDER CHAR(1),
SSN VARCHAR(13) NOT NULL UNIQUE,
PHONE CHAR(10) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
ADDRESS VARCHAR(50) NOT NULL,
CITY VARCHAR(50) NOT NULL,
STATES CHAR(2) NOT NULL,
ZIP_CODE CHAR(6) NOT NULL,
FOREIGN KEY(EMAIL) REFERENCES Customer(email));

CREATE TABLE EMPLOYEES(
EMPLOYEE_ID INT NOT NULL PRIMARY KEY,
FIRST_NAME VARCHAR(25) NOT NULL,
M_NAME VARCHAR(25) NOT NULL,
LAST_NAME VARCHAR(25) NOT NULL,
DATE_BIRTH DATE NOT NULL,
GENDER CHAR(1),
SSN CHAR(9) NOT NULL UNIQUE PRIMARY KEY,
PHONE CHAR(9) NOT NULL,
EMAIL VARCHAR(50) NOT NULL UNIQUE,
ADDRESS VARCHAR(50) NOT NULL,
CITY VARCHAR(20) NOT NULL,
STATES CHAR(2) NOT NULL,
ZIP_CODE CHAR(6) NOT NULL,
FOREIGN KEY(EMAIL) REFERENCES employee_user(email));

CREATE TABLE DEPARTMENT(
DEPART_ID VARCHAR NOT NULL UNIQUE PRIMARY KEY,
EMPLOYEE_ID INT NOT NULL,
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID),
DEPART_NAME VARCHAR(40),
DEPART_PHONE CHAR(9)
DEPART_JOB VARCHAR(40));

CREATE TABLE PRODUCTS(
VEND_NUMBER INT NULL UNIQUE PRIMARY KEY,
NAME VARCHAR(30) NOT NULL,
BRAND VARCHAR(30) NOT NULL,
discreption varchar(100) NOT NULL,
CASE_COUNT CHAR(2) NOT NULL,
CASE_PRICE FLOAT(3) NOT NULL);

CREATE TABLE CUSTOMER_ORDER(
ORDER_ID INT NOT NULL PRIMARY KEY,
VEND_NUMBER INT  NOT NULL UNIQUE,
FOREIGN KEY (VEND_NUMBER) REFERENCES PRODUCTS(VEND_NUMBER),
TOTAL_COST FLOAT(2),
ORDER_STATUS VARCHAR(30),
ORDER_DATE TIMESTAMP,
DELIEVERY_DATE DATE );

CREATE TABLE PAY_STATEMENT(
PAY_ID INT NOT NULL,PRIMARY KEY,
EMPLOYEE_ID INT NOT NULL,
FOREIGN KEY EMPLOYEE_ID REFERENCES EMPLOYEES(EMPLOYEE_ID),
START_WEEK DATE,
END_WEEK DATE,
PAY_RATE FLOAT(2),
TOTAL_PAY FLOAT(3),
TOTAL_TAX) FLOAT(2));